baseURL = 'https://oda.world'
languageCode = 'ja'
title = 'ODA WORLD'
canonifyurls = true
hasCJKLanguage = true
copyright = "© 2021 ODA WORLD"
paginate = 12
enableGitInfo = true

[frontmatter]
  lastmod = [':git', 'lastmod']

[params]
  twitter = "@oskfjzp"
  facebook = "last.pass.oda"
  github = "GOD-oda"
  defaultOgImage = '/images/ogImage/default.png'
  siteName = 'ODA WORLD'
  siteDescription = 'GOD-odaが運営するブログ'
  author = "GOD-oda"

[markup]
  [markup.highlight]
    codeFences = true
    lineNoStart = 1
    lineNumbersInTable = true
    noClasses = true
  [markup.tableOfContents]
    endLevel = 3
    startLevel = 1