version: '3.8'
services:
  dynamodb:
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath . -optimizeDbBeforeStartup"
    image: amazon/dynamodb-local
    ports:
      - "8000:8000"
    volumes:
      - "dynamodb:/home/dynamodblocal"
volumes:
  dynamodb:
    driver: local

