version: '3.8'
services:
  dynamodb:
    image: amazon/dynamodb-local
    command: "-jar DynamoDBLocal.jar -dbPath ."
    ports:
      - "8000:8000"
    volumes:
      - "dynamodb:/home/dynamodblocal"
volumes:
  dynamodb:
    driver: local

