version: "3.9"
services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - type: bind
        source: ./src
        target: /var/www/html
    ports:
      - "8080:80"
    working_dir: /var/www/html