template: twitterCard/template.png
title:
  start:
    px: 300
    py: 300
  fgHexColor: "#FFFFFF"
  fontSize: 256
  fontStyle: Bold
  maxWidth: 4000
  lineSpacing: 10
category:
  start:
    px: 0
    py: 0
  fgHexColor: "#E5B52A"
  fontSize: 1
  fontStyle: Regular
info:
  start:
    px: 2500
    py: 2500
  fgHexColor: "#FFFFFFF"
  fontSize: 150
  fontStyle: Regular
  separator: " / "
tags:
  start:
    px: 300
    py: 2000
  fgHexColor: "#999999"
  bgHexColor: "#FFFFFF"
  fontSize: 75
  fontStyle: Medium
  boxAlign: Left
  boxSpacing: 10
  boxPadding:
    top: 20
    right: 20
    bottom: 20
    left: 20
